GET http://localhost:8000/api/posts/

###

GET http://localhost:8000/api/postsFull/

###

GET http://localhost:8000/api/posts/5e905d7ba87c9a31d048da07

###

POST http://localhost:8000/api/posts/
content-type: application/json

{
  "title": "test Title",
  "price": 25,
  "content": "testContent testContent testContent",
  "email": "testEmail@test.test",
  "telephone": "213456456"
}

###

PUT http://localhost:8000/api/posts/5e9062950e71d4322470e7ec
content-type: application/json

{
  "title": "test Title2",
  "price": 252,
  "content": "testContent2 testContent2 testContent2",
  "email": "testEmail2@test2.test2",
  "telephone": "222222222"
}